version: '3.8'

services:
  web_app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      FLASK_APP: core/server.py
    volumes:
      - .:/app
    command: bash run.sh